/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  timestamp,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_brands_currency = pgEnum('enum_brands_currency', ['EUR', 'GBP', 'USD'])
export const enum_plans_cadence = pgEnum('enum_plans_cadence', [
  'monthly',
  'bi_monthly',
  'quarterly',
])
export const enum_plans_currency = pgEnum('enum_plans_currency', ['EUR', 'GBP', 'USD'])
export const enum_wines_style = pgEnum('enum_wines_style', [
  'red',
  'white',
  'rosé',
  'orange',
  'sparkling',
  'fortified',
])
export const enum_wine_skus_currency = pgEnum('enum_wine_skus_currency', ['EUR', 'GBP', 'USD'])
export const enum_grapes_colour = pgEnum('enum_grapes_colour', ['red', 'white', 'pink', 'grey'])
export const enum_editions_release_state = pgEnum('enum_editions_release_state', [
  'draft',
  'preview',
  'live',
  'archived',
])
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor'])

export const brands_hostnames = pgTable(
  'brands_hostnames',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    hostname: varchar('hostname').notNull(),
  },
  (columns) => [
    index('brands_hostnames_order_idx').on(columns._order),
    index('brands_hostnames_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [brands.id],
      name: 'brands_hostnames_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const brands = pgTable(
  'brands',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    currency: enum_brands_currency('currency').notNull().default('EUR'),
    theme_ink: varchar('theme_ink').notNull().default('#171714'),
    theme_cream: varchar('theme_cream').notNull().default('#F3EFE4'),
    theme_accent: varchar('theme_accent').notNull().default('#B65F43'),
    theme_secondary: varchar('theme_secondary').notNull().default('#35483A'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('brands_slug_idx').on(columns.slug),
    index('brands_updated_at_idx').on(columns.updatedAt),
    index('brands_created_at_idx').on(columns.createdAt),
  ],
)

export const plans = pgTable(
  'plans',
  {
    id: serial('id').primaryKey(),
    brand: integer('brand_id')
      .notNull()
      .references(() => brands.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    code: varchar('code').notNull(),
    description: varchar('description'),
    cadence: enum_plans_cadence('cadence').notNull(),
    bottlesPerBox: numeric('bottles_per_box', { mode: 'number' }).notNull(),
    priceAmount: numeric('price_amount', { mode: 'number' }).notNull(),
    currency: enum_plans_currency('currency').notNull().default('EUR'),
    externalPriceId: varchar('external_price_id'),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('plans_brand_idx').on(columns.brand),
    uniqueIndex('plans_code_idx').on(columns.code),
    index('plans_updated_at_idx').on(columns.updatedAt),
    index('plans_created_at_idx').on(columns.createdAt),
  ],
)

export const wines = pgTable(
  'wines',
  {
    id: serial('id').primaryKey(),
    brand: integer('brand_id')
      .notNull()
      .references(() => brands.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    producer: integer('producer_id')
      .notNull()
      .references(() => producers.id, {
        onDelete: 'set null',
      }),
    country: integer('country_id')
      .notNull()
      .references(() => countries.id, {
        onDelete: 'set null',
      }),
    region: integer('region_id')
      .notNull()
      .references(() => regions.id, {
        onDelete: 'set null',
      }),
    vintage: numeric('vintage', { mode: 'number' }),
    style: enum_wines_style('style'),
    story: jsonb('story'),
    label: integer('label_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('wines_brand_idx').on(columns.brand),
    uniqueIndex('wines_slug_idx').on(columns.slug),
    index('wines_producer_idx').on(columns.producer),
    index('wines_country_idx').on(columns.country),
    index('wines_region_idx').on(columns.region),
    index('wines_label_idx').on(columns.label),
    index('wines_updated_at_idx').on(columns.updatedAt),
    index('wines_created_at_idx').on(columns.createdAt),
  ],
)

export const wines_rels = pgTable(
  'wines_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    grapesID: integer('grapes_id'),
  },
  (columns) => [
    index('wines_rels_order_idx').on(columns.order),
    index('wines_rels_parent_idx').on(columns.parent),
    index('wines_rels_path_idx').on(columns.path),
    index('wines_rels_grapes_id_idx').on(columns.grapesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [wines.id],
      name: 'wines_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['grapesID']],
      foreignColumns: [grapes.id],
      name: 'wines_rels_grapes_fk',
    }).onDelete('cascade'),
  ],
)

export const wine_skus = pgTable(
  'wine_skus',
  {
    id: serial('id').primaryKey(),
    wine: integer('wine_id')
      .notNull()
      .references(() => wines.id, {
        onDelete: 'set null',
      }),
    sku: varchar('sku').notNull(),
    bottleSizeMl: numeric('bottle_size_ml', { mode: 'number' }).notNull().default(750),
    priceAmount: numeric('price_amount', { mode: 'number' }).notNull(),
    currency: enum_wine_skus_currency('currency').notNull().default('EUR'),
    active: boolean('active').default(true),
    externalProductId: varchar('external_product_id'),
    externalPriceId: varchar('external_price_id'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('wine_skus_wine_idx').on(columns.wine),
    uniqueIndex('wine_skus_sku_idx').on(columns.sku),
    index('wine_skus_updated_at_idx').on(columns.updatedAt),
    index('wine_skus_created_at_idx').on(columns.createdAt),
  ],
)

export const producers = pgTable(
  'producers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    country: integer('country_id')
      .notNull()
      .references(() => countries.id, {
        onDelete: 'set null',
      }),
    region: integer('region_id').references(() => regions.id, {
      onDelete: 'set null',
    }),
    portrait: integer('portrait_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    story: jsonb('story'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('producers_slug_idx').on(columns.slug),
    index('producers_country_idx').on(columns.country),
    index('producers_region_idx').on(columns.region),
    index('producers_portrait_idx').on(columns.portrait),
    index('producers_updated_at_idx').on(columns.updatedAt),
    index('producers_created_at_idx').on(columns.createdAt),
  ],
)

export const producers_rels = pgTable(
  'producers_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    brandsID: integer('brands_id'),
  },
  (columns) => [
    index('producers_rels_order_idx').on(columns.order),
    index('producers_rels_parent_idx').on(columns.parent),
    index('producers_rels_path_idx').on(columns.path),
    index('producers_rels_brands_id_idx').on(columns.brandsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [producers.id],
      name: 'producers_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['brandsID']],
      foreignColumns: [brands.id],
      name: 'producers_rels_brands_fk',
    }).onDelete('cascade'),
  ],
)

export const countries = pgTable(
  'countries',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('countries_code_idx').on(columns.code),
    index('countries_updated_at_idx').on(columns.updatedAt),
    index('countries_created_at_idx').on(columns.createdAt),
  ],
)

export const regions = pgTable(
  'regions',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    country: integer('country_id')
      .notNull()
      .references(() => countries.id, {
        onDelete: 'set null',
      }),
    story: jsonb('story'),
    hero: integer('hero_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('regions_slug_idx').on(columns.slug),
    index('regions_country_idx').on(columns.country),
    index('regions_hero_idx').on(columns.hero),
    index('regions_updated_at_idx').on(columns.updatedAt),
    index('regions_created_at_idx').on(columns.createdAt),
  ],
)

export const grapes_aliases = pgTable(
  'grapes_aliases',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
  },
  (columns) => [
    index('grapes_aliases_order_idx').on(columns._order),
    index('grapes_aliases_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [grapes.id],
      name: 'grapes_aliases_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const grapes = pgTable(
  'grapes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    colour: enum_grapes_colour('colour'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('grapes_name_idx').on(columns.name),
    index('grapes_updated_at_idx').on(columns.updatedAt),
    index('grapes_created_at_idx').on(columns.createdAt),
  ],
)

export const editions = pgTable(
  'editions',
  {
    id: serial('id').primaryKey(),
    brand: integer('brand_id')
      .notNull()
      .references(() => brands.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    releaseState: enum_editions_release_state('release_state').notNull().default('draft'),
    opensAt: timestamp('opens_at', { mode: 'string', withTimezone: true, precision: 3 }),
    closesAt: timestamp('closes_at', { mode: 'string', withTimezone: true, precision: 3 }),
    region: integer('region_id').references(() => regions.id, {
      onDelete: 'set null',
    }),
    hero: integer('hero_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    narrative: jsonb('narrative'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('editions_brand_idx').on(columns.brand),
    uniqueIndex('editions_slug_idx').on(columns.slug),
    index('editions_region_idx').on(columns.region),
    index('editions_hero_idx').on(columns.hero),
    index('editions_updated_at_idx').on(columns.updatedAt),
    index('editions_created_at_idx').on(columns.createdAt),
  ],
)

export const boxes = pgTable(
  'boxes',
  {
    id: serial('id').primaryKey(),
    brand: integer('brand_id')
      .notNull()
      .references(() => brands.id, {
        onDelete: 'set null',
      }),
    edition: integer('edition_id')
      .notNull()
      .references(() => editions.id, {
        onDelete: 'set null',
      }),
    plan: integer('plan_id')
      .notNull()
      .references(() => plans.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    packingNote: varchar('packing_note'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('boxes_brand_idx').on(columns.brand),
    index('boxes_edition_idx').on(columns.edition),
    index('boxes_plan_idx').on(columns.plan),
    index('boxes_updated_at_idx').on(columns.updatedAt),
    index('boxes_created_at_idx').on(columns.createdAt),
  ],
)

export const boxes_rels = pgTable(
  'boxes_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'wine-skusID': integer('wine_skus_id'),
  },
  (columns) => [
    index('boxes_rels_order_idx').on(columns.order),
    index('boxes_rels_parent_idx').on(columns.parent),
    index('boxes_rels_path_idx').on(columns.path),
    index('boxes_rels_wine_skus_id_idx').on(columns['wine-skusID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [boxes.id],
      name: 'boxes_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['wine-skusID']],
      foreignColumns: [wine_skus.id],
      name: 'boxes_rels_wine_skus_fk',
    }).onDelete('cascade'),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    caption: varchar('caption'),
    credit: varchar('credit'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_card_url: varchar('sizes_card_url'),
    sizes_card_width: numeric('sizes_card_width', { mode: 'number' }),
    sizes_card_height: numeric('sizes_card_height', { mode: 'number' }),
    sizes_card_mimeType: varchar('sizes_card_mime_type'),
    sizes_card_filesize: numeric('sizes_card_filesize', { mode: 'number' }),
    sizes_card_filename: varchar('sizes_card_filename'),
    sizes_wide_url: varchar('sizes_wide_url'),
    sizes_wide_width: numeric('sizes_wide_width', { mode: 'number' }),
    sizes_wide_height: numeric('sizes_wide_height', { mode: 'number' }),
    sizes_wide_mimeType: varchar('sizes_wide_mime_type'),
    sizes_wide_filesize: numeric('sizes_wide_filesize', { mode: 'number' }),
    sizes_wide_filename: varchar('sizes_wide_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename),
    index('media_sizes_wide_sizes_wide_filename_idx').on(columns.sizes_wide_filename),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    role: enum_users_role('role').notNull().default('editor'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    brandsID: integer('brands_id'),
    plansID: integer('plans_id'),
    winesID: integer('wines_id'),
    'wine-skusID': integer('wine_skus_id'),
    producersID: integer('producers_id'),
    countriesID: integer('countries_id'),
    regionsID: integer('regions_id'),
    grapesID: integer('grapes_id'),
    editionsID: integer('editions_id'),
    boxesID: integer('boxes_id'),
    mediaID: integer('media_id'),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_brands_id_idx').on(columns.brandsID),
    index('payload_locked_documents_rels_plans_id_idx').on(columns.plansID),
    index('payload_locked_documents_rels_wines_id_idx').on(columns.winesID),
    index('payload_locked_documents_rels_wine_skus_id_idx').on(columns['wine-skusID']),
    index('payload_locked_documents_rels_producers_id_idx').on(columns.producersID),
    index('payload_locked_documents_rels_countries_id_idx').on(columns.countriesID),
    index('payload_locked_documents_rels_regions_id_idx').on(columns.regionsID),
    index('payload_locked_documents_rels_grapes_id_idx').on(columns.grapesID),
    index('payload_locked_documents_rels_editions_id_idx').on(columns.editionsID),
    index('payload_locked_documents_rels_boxes_id_idx').on(columns.boxesID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['brandsID']],
      foreignColumns: [brands.id],
      name: 'payload_locked_documents_rels_brands_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['plansID']],
      foreignColumns: [plans.id],
      name: 'payload_locked_documents_rels_plans_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['winesID']],
      foreignColumns: [wines.id],
      name: 'payload_locked_documents_rels_wines_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['wine-skusID']],
      foreignColumns: [wine_skus.id],
      name: 'payload_locked_documents_rels_wine_skus_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['producersID']],
      foreignColumns: [producers.id],
      name: 'payload_locked_documents_rels_producers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'payload_locked_documents_rels_countries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['regionsID']],
      foreignColumns: [regions.id],
      name: 'payload_locked_documents_rels_regions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['grapesID']],
      foreignColumns: [grapes.id],
      name: 'payload_locked_documents_rels_grapes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['editionsID']],
      foreignColumns: [editions.id],
      name: 'payload_locked_documents_rels_editions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['boxesID']],
      foreignColumns: [boxes.id],
      name: 'payload_locked_documents_rels_boxes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_brands_hostnames = relations(brands_hostnames, ({ one }) => ({
  _parentID: one(brands, {
    fields: [brands_hostnames._parentID],
    references: [brands.id],
    relationName: 'hostnames',
  }),
}))
export const relations_brands = relations(brands, ({ many }) => ({
  hostnames: many(brands_hostnames, {
    relationName: 'hostnames',
  }),
}))
export const relations_plans = relations(plans, ({ one }) => ({
  brand: one(brands, {
    fields: [plans.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
}))
export const relations_wines_rels = relations(wines_rels, ({ one }) => ({
  parent: one(wines, {
    fields: [wines_rels.parent],
    references: [wines.id],
    relationName: '_rels',
  }),
  grapesID: one(grapes, {
    fields: [wines_rels.grapesID],
    references: [grapes.id],
    relationName: 'grapes',
  }),
}))
export const relations_wines = relations(wines, ({ one, many }) => ({
  brand: one(brands, {
    fields: [wines.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
  producer: one(producers, {
    fields: [wines.producer],
    references: [producers.id],
    relationName: 'producer',
  }),
  country: one(countries, {
    fields: [wines.country],
    references: [countries.id],
    relationName: 'country',
  }),
  region: one(regions, {
    fields: [wines.region],
    references: [regions.id],
    relationName: 'region',
  }),
  label: one(media, {
    fields: [wines.label],
    references: [media.id],
    relationName: 'label',
  }),
  _rels: many(wines_rels, {
    relationName: '_rels',
  }),
}))
export const relations_wine_skus = relations(wine_skus, ({ one }) => ({
  wine: one(wines, {
    fields: [wine_skus.wine],
    references: [wines.id],
    relationName: 'wine',
  }),
}))
export const relations_producers_rels = relations(producers_rels, ({ one }) => ({
  parent: one(producers, {
    fields: [producers_rels.parent],
    references: [producers.id],
    relationName: '_rels',
  }),
  brandsID: one(brands, {
    fields: [producers_rels.brandsID],
    references: [brands.id],
    relationName: 'brands',
  }),
}))
export const relations_producers = relations(producers, ({ one, many }) => ({
  country: one(countries, {
    fields: [producers.country],
    references: [countries.id],
    relationName: 'country',
  }),
  region: one(regions, {
    fields: [producers.region],
    references: [regions.id],
    relationName: 'region',
  }),
  portrait: one(media, {
    fields: [producers.portrait],
    references: [media.id],
    relationName: 'portrait',
  }),
  _rels: many(producers_rels, {
    relationName: '_rels',
  }),
}))
export const relations_countries = relations(countries, () => ({}))
export const relations_regions = relations(regions, ({ one }) => ({
  country: one(countries, {
    fields: [regions.country],
    references: [countries.id],
    relationName: 'country',
  }),
  hero: one(media, {
    fields: [regions.hero],
    references: [media.id],
    relationName: 'hero',
  }),
}))
export const relations_grapes_aliases = relations(grapes_aliases, ({ one }) => ({
  _parentID: one(grapes, {
    fields: [grapes_aliases._parentID],
    references: [grapes.id],
    relationName: 'aliases',
  }),
}))
export const relations_grapes = relations(grapes, ({ many }) => ({
  aliases: many(grapes_aliases, {
    relationName: 'aliases',
  }),
}))
export const relations_editions = relations(editions, ({ one }) => ({
  brand: one(brands, {
    fields: [editions.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
  region: one(regions, {
    fields: [editions.region],
    references: [regions.id],
    relationName: 'region',
  }),
  hero: one(media, {
    fields: [editions.hero],
    references: [media.id],
    relationName: 'hero',
  }),
}))
export const relations_boxes_rels = relations(boxes_rels, ({ one }) => ({
  parent: one(boxes, {
    fields: [boxes_rels.parent],
    references: [boxes.id],
    relationName: '_rels',
  }),
  'wine-skusID': one(wine_skus, {
    fields: [boxes_rels['wine-skusID']],
    references: [wine_skus.id],
    relationName: 'wine-skus',
  }),
}))
export const relations_boxes = relations(boxes, ({ one, many }) => ({
  brand: one(brands, {
    fields: [boxes.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
  edition: one(editions, {
    fields: [boxes.edition],
    references: [editions.id],
    relationName: 'edition',
  }),
  plan: one(plans, {
    fields: [boxes.plan],
    references: [plans.id],
    relationName: 'plan',
  }),
  _rels: many(boxes_rels, {
    relationName: '_rels',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    brandsID: one(brands, {
      fields: [payload_locked_documents_rels.brandsID],
      references: [brands.id],
      relationName: 'brands',
    }),
    plansID: one(plans, {
      fields: [payload_locked_documents_rels.plansID],
      references: [plans.id],
      relationName: 'plans',
    }),
    winesID: one(wines, {
      fields: [payload_locked_documents_rels.winesID],
      references: [wines.id],
      relationName: 'wines',
    }),
    'wine-skusID': one(wine_skus, {
      fields: [payload_locked_documents_rels['wine-skusID']],
      references: [wine_skus.id],
      relationName: 'wine-skus',
    }),
    producersID: one(producers, {
      fields: [payload_locked_documents_rels.producersID],
      references: [producers.id],
      relationName: 'producers',
    }),
    countriesID: one(countries, {
      fields: [payload_locked_documents_rels.countriesID],
      references: [countries.id],
      relationName: 'countries',
    }),
    regionsID: one(regions, {
      fields: [payload_locked_documents_rels.regionsID],
      references: [regions.id],
      relationName: 'regions',
    }),
    grapesID: one(grapes, {
      fields: [payload_locked_documents_rels.grapesID],
      references: [grapes.id],
      relationName: 'grapes',
    }),
    editionsID: one(editions, {
      fields: [payload_locked_documents_rels.editionsID],
      references: [editions.id],
      relationName: 'editions',
    }),
    boxesID: one(boxes, {
      fields: [payload_locked_documents_rels.boxesID],
      references: [boxes.id],
      relationName: 'boxes',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_brands_currency: typeof enum_brands_currency
  enum_plans_cadence: typeof enum_plans_cadence
  enum_plans_currency: typeof enum_plans_currency
  enum_wines_style: typeof enum_wines_style
  enum_wine_skus_currency: typeof enum_wine_skus_currency
  enum_grapes_colour: typeof enum_grapes_colour
  enum_editions_release_state: typeof enum_editions_release_state
  enum_users_role: typeof enum_users_role
  brands_hostnames: typeof brands_hostnames
  brands: typeof brands
  plans: typeof plans
  wines: typeof wines
  wines_rels: typeof wines_rels
  wine_skus: typeof wine_skus
  producers: typeof producers
  producers_rels: typeof producers_rels
  countries: typeof countries
  regions: typeof regions
  grapes_aliases: typeof grapes_aliases
  grapes: typeof grapes
  editions: typeof editions
  boxes: typeof boxes
  boxes_rels: typeof boxes_rels
  media: typeof media
  users_sessions: typeof users_sessions
  users: typeof users
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_brands_hostnames: typeof relations_brands_hostnames
  relations_brands: typeof relations_brands
  relations_plans: typeof relations_plans
  relations_wines_rels: typeof relations_wines_rels
  relations_wines: typeof relations_wines
  relations_wine_skus: typeof relations_wine_skus
  relations_producers_rels: typeof relations_producers_rels
  relations_producers: typeof relations_producers
  relations_countries: typeof relations_countries
  relations_regions: typeof relations_regions
  relations_grapes_aliases: typeof relations_grapes_aliases
  relations_grapes: typeof relations_grapes
  relations_editions: typeof relations_editions
  relations_boxes_rels: typeof relations_boxes_rels
  relations_boxes: typeof relations_boxes
  relations_media: typeof relations_media
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
